create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,role text not null default 'guest' check(role in ('admin','guest')),created_at timestamptz not null default now());
create table if not exists public.posts(id bigint generated by default as identity primary key,title text not null,description text,file_path text not null unique,mime_type text,created_at timestamptz not null default now());
create table if not exists public.comments(id bigint generated by default as identity primary key,post_id bigint not null references public.posts(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,guest_name text not null,body text not null,created_at timestamptz not null default now());
create table if not exists public.likes(id bigint generated by default as identity primary key,post_id bigint not null references public.posts(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,created_at timestamptz not null default now(),unique(post_id,user_id));

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.likes enable row level security;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin') $$;
grant execute on function public.is_admin() to anon,authenticated;
grant usage on schema public to anon,authenticated;
grant select on public.posts,public.comments,public.likes to anon,authenticated;
grant insert,delete on public.posts to authenticated;
grant insert on public.comments,public.likes to authenticated;
grant usage,select on all sequences in schema public to anon,authenticated;

drop policy if exists ah_posts_read on public.posts;
create policy ah_posts_read on public.posts for select using(true);
drop policy if exists ah_posts_insert on public.posts;
create policy ah_posts_insert on public.posts for insert to authenticated with check(public.is_admin());
drop policy if exists ah_posts_delete on public.posts;
create policy ah_posts_delete on public.posts for delete to authenticated using(public.is_admin());
drop policy if exists ah_comments_read on public.comments;
create policy ah_comments_read on public.comments for select using(true);
drop policy if exists ah_comments_insert on public.comments;
create policy ah_comments_insert on public.comments for insert to authenticated with check(auth.uid()=user_id);
drop policy if exists ah_likes_read on public.likes;
create policy ah_likes_read on public.likes for select using(true);
drop policy if exists ah_likes_insert on public.likes;
create policy ah_likes_insert on public.likes for insert to authenticated with check(auth.uid()=user_id);

insert into storage.buckets(id,name,public,file_size_limit) values('media','media',true,52428800) on conflict(id) do update set public=true,file_size_limit=52428800;
drop policy if exists ah_media_read on storage.objects;
create policy ah_media_read on storage.objects for select using(bucket_id='media');
drop policy if exists ah_media_insert on storage.objects;
create policy ah_media_insert on storage.objects for insert to authenticated with check(bucket_id='media' and public.is_admin());
drop policy if exists ah_media_delete on storage.objects;
create policy ah_media_delete on storage.objects for delete to authenticated using(bucket_id='media' and public.is_admin());

do $$ begin
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='comments') then execute 'alter publication supabase_realtime add table public.comments'; end if;
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='likes') then execute 'alter publication supabase_realtime add table public.likes'; end if;
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='posts') then execute 'alter publication supabase_realtime add table public.posts'; end if;
end $$;

-- After creating the admin user in Supabase Authentication, replace USER-UUID-HERE with its actual UUID and run this statement:
-- insert into public.profiles(id,full_name,role) values('USER-UUID-HERE','ادمین','admin') on conflict(id) do update set role='admin',full_name='ادمین';
